
create_clock -period 14.000 -waveform {0.000 7.000} [get_ports clk_30MHz]

set_input_delay -clock [get_clocks clk_30MHz] -min -add_delay 0.000 [get_ports {control_sel[*]}]
set_input_delay -clock [get_clocks clk_30MHz] -max -add_delay 2.000 [get_ports {control_sel[*]}]
set_input_delay -clock [get_clocks clk_30MHz] -min -add_delay 0.000 [get_ports {s00_axis_0_tdata[*]}]
set_input_delay -clock [get_clocks clk_30MHz] -max -add_delay 2.000 [get_ports {s00_axis_0_tdata[*]}]
set_input_delay -clock [get_clocks clk_30MHz] -min -add_delay 0.000 [get_ports m00_axis_0_tready]
set_input_delay -clock [get_clocks clk_30MHz] -max -add_delay 2.000 [get_ports m00_axis_0_tready]
set_input_delay -clock [get_clocks clk_30MHz] -min -add_delay 0.000 [get_ports reset]
set_input_delay -clock [get_clocks clk_30MHz] -max -add_delay 2.000 [get_ports reset]
set_input_delay -clock [get_clocks clk_30MHz] -min -add_delay 0.000 [get_ports s00_axis_0_tvalid]
set_input_delay -clock [get_clocks clk_30MHz] -max -add_delay 2.000 [get_ports s00_axis_0_tvalid]
set_output_delay -clock [get_clocks clk_30MHz] -min -add_delay 0.000 [get_ports {m00_axis_0_tdata[*]}]
set_output_delay -clock [get_clocks clk_30MHz] -max -add_delay 0.000 [get_ports {m00_axis_0_tdata[*]}]
set_output_delay -clock [get_clocks clk_30MHz] -min -add_delay 0.000 [get_ports m00_axis_0_tlast]
set_output_delay -clock [get_clocks clk_30MHz] -max -add_delay 0.000 [get_ports m00_axis_0_tlast]
set_output_delay -clock [get_clocks clk_30MHz] -min -add_delay 0.000 [get_ports m00_axis_0_tvalid]
set_output_delay -clock [get_clocks clk_30MHz] -max -add_delay 0.000 [get_ports m00_axis_0_tvalid]
set_output_delay -clock [get_clocks clk_30MHz] -min -add_delay 0.000 [get_ports s00_axis_0_tready]
set_output_delay -clock [get_clocks clk_30MHz] -max -add_delay 0.000 [get_ports s00_axis_0_tready]
set_property IOSTANDARD HSLVDCI_15 [get_ports clk_30MHz]




#set_property BEL CARRY4 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/man_abT0_inferred__0/i__carry}]
#set_property BEL CARRY4 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/man_abT0_inferred__0/i__carry__1}]
#set_property BEL CARRY4 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/shift_amount10_carry}]
#set_property BEL D6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/sumout[17]_i_3__9}]
#set_property BEL A6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry_i_29__1}]
#set_property BEL C6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry__1_i_27__1}]
#set_property BEL B6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/sign_abT1_carry_i_14__1}]
#set_property BEL B6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/sumout[4]_i_6__7}]
#set_property BEL C6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry_i_51__7}]
#set_property BEL C6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry__0_i_25__1}]
#set_property BEL C6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/man_abT0_carry_i_48__7}]
#set_property BEL BFF [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/sumout_reg[16]}]
#set_property BEL C6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/LZC32.LZC54/sumout[21]_i_8__9}]
#set_property BEL D6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry__1_i_32__7}]
#set_property BEL CARRY4 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/shift_amount10_carry__0}]
#set_property BEL A6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry__0_i_34__7}]
#set_property BEL B6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/man_abT0_carry__4_i_12__7}]
#set_property BEL CARRY4 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/man_abT0_inferred__0/i__carry__0}]
#set_property BEL B6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry__0_i_36__7}]
#set_property BEL D6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/sign_abT1_carry_i_22__1}]
#set_property BEL C6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/man_abT0_carry_i_47__7}]
#set_property BEL B6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/sign_abT1_carry_i_7__7}]
#set_property BEL CARRY4 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry_i_17__13}]
#set_property BEL AFF [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/mode_buffer_reg[1][7]}]
#set_property BEL CARRY4 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/sign_abT1_carry}]
#set_property BEL B6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/sumout[16]_i_1__9}]
#set_property BEL A6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry__0_i_30__7}]
#set_property BEL A6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/sign_abT1_carry_i_31__7}]
#set_property BEL B5LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/shift_amount10_carry_i_3__7}]
#set_property BEL A6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/man_abT0_carry_i_16__7}]
#set_property BEL B6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/LZC32.LZC54/first_valid_block_reg[2]_i_22__7}]
#set_property BEL D6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/Lbd_b_reg[4]_i_1__9}]
#set_property BEL B6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/man_abT0_carry_i_36__7}]
#set_property BEL D6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/sumout[4]_i_14__1}]
#set_property BEL A6LUT [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/man_abT0_carry_i_3__7}]
#set_property LOC SLICE_X49Y29 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/man_abT0_inferred__0/i__carry}]
#set_property LOC SLICE_X49Y31 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/man_abT0_inferred__0/i__carry__1}]
#set_property LOC SLICE_X41Y30 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/shift_amount10_carry}]
#set_property LOC SLICE_X56Y35 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/sumout[17]_i_3__9}]
#set_property LOC SLICE_X32Y30 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry_i_29__1}]
#set_property LOC SLICE_X37Y30 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry__1_i_27__1}]
#set_property LOC SLICE_X39Y31 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/sign_abT1_carry_i_14__1}]
#set_property LOC SLICE_X55Y34 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/sumout[4]_i_6__7}]
#set_property LOC SLICE_X29Y30 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry_i_51__7}]
#set_property LOC SLICE_X36Y30 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry__0_i_25__1}]
#set_property LOC SLICE_X46Y31 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/man_abT0_carry_i_48__7}]
#set_property LOC SLICE_X59Y34 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/sumout_reg[16]}]
#set_property LOC SLICE_X57Y34 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/LZC32.LZC54/sumout[21]_i_8__9}]
#set_property LOC SLICE_X36Y30 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry__1_i_32__7}]
#set_property LOC SLICE_X41Y31 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/shift_amount10_carry__0}]
#set_property LOC SLICE_X33Y31 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry__0_i_34__7}]
#set_property LOC SLICE_X43Y31 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/man_abT0_carry__4_i_12__7}]
#set_property LOC SLICE_X49Y30 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/man_abT0_inferred__0/i__carry__0}]
#set_property LOC SLICE_X33Y31 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry__0_i_36__7}]
#set_property LOC SLICE_X39Y31 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/sign_abT1_carry_i_22__1}]
#set_property LOC SLICE_X42Y32 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/man_abT0_carry_i_47__7}]
#set_property LOC SLICE_X40Y30 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/sign_abT1_carry_i_7__7}]
#set_property LOC SLICE_X32Y30 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry_i_17__13}]
#set_property LOC SLICE_X31Y31 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/mode_buffer_reg[1][7]}]
#set_property LOC SLICE_X40Y30 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/sign_abT1_carry}]
#set_property LOC SLICE_X59Y34 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/sumout[16]_i_1__9}]
#set_property LOC SLICE_X36Y31 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/i__carry__0_i_30__7}]
#set_property LOC SLICE_X38Y31 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/sign_abT1_carry_i_31__7}]
#set_property LOC SLICE_X41Y30 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/shift_amount10_carry_i_3__7}]
#set_property LOC SLICE_X46Y31 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/man_abT0_carry_i_16__7}]
#set_property LOC SLICE_X52Y31 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/LZC32.LZC54/first_valid_block_reg[2]_i_22__7}]
#set_property LOC SLICE_X31Y30 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/Lbd_b_reg[4]_i_1__9}]
#set_property LOC SLICE_X43Y30 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/man_abT0_carry_i_36__7}]
#set_property LOC SLICE_X54Y33 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/fp_add/sumout[4]_i_14__1}]
#set_property LOC SLICE_X48Y29 [get_cells {design_1_i/SysA_interface_pipe1_0/U0/systolic/gen_rows[1].gen_cols[1].PE/kacy/man_abT0_carry_i_3__7}]
